version: '3'
services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    image: atulkkushwaha92/ecommerce-react-ui
    ports:
    environment:
      - WEBSITE_IMAGE=atulkkushwaha92/ecommerce-react-ui
      - '3000:3000'
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
volumes:
  client: