version: '3'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
        - ./mysql-db/user.sql:/docker-entrypoint-initdb.d/user.sql
    ports:
      - 3306:3306

  authentication-service:
    build:
      context: .
      dockerfile: ./server/authentication-service/Dockerfile-dev
    container_name: authentication-service-container
    restart: always
    depends_on:
      - mysql-db
      - react-ui
    environment:
      - DB_HOST=mysql-db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_SCHEMA=${DB_SCHEMA}
      - ACTIVE_PROFILE=${ACTIVE_PROFILE}
      - PORT=${AUTHENTICATION_SERVICE_PORT}
    links:
      - mysql-db:mysql
    expose:
      - ${AUTHENTICATION_SERVICE_PORT}
    ports:
      - ${AUTHENTICATION_SERVICE_PORT}:${AUTHENTICATION_SERVICE_PORT}
    networks:
      - spring-cloud-microservices

  common-data-service:
    build:
      context: .
      dockerfile: ./server/common-data-service/Dockerfile-dev
    container_name: common-data-service-container
    restart: always
    depends_on:
      - mysql-db
      - redis-cache
      - react-ui
    environment:
      - DB_HOST=mysql-db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_SCHEMA=${DB_SCHEMA}
      - ACTIVE_PROFILE=${ACTIVE_PROFILE}
      - PORT=${COMMON_DATA_SERVICE_PORT}
      - REACT_CLIENT_URL=${REACT_CLIENT_URL}
    links:
      - mysql-db:mysql
    expose:
      - ${COMMON_DATA_SERVICE_PORT}
    ports:
      - ${COMMON_DATA_SERVICE_PORT}:${COMMON_DATA_SERVICE_PORT}

  search-elastic-service:
    build:
      context: .
      dockerfile: ./server/search-elastic-service/Dockerfile-dev
    container_name: search-elastic-service-container
    restart: always
    depends_on:
      - mysql-db
      - react-ui
      - common-data-service
      - authentication-service
    environment:
      - ACTIVE_PROFILE=${ACTIVE_PROFILE}
      - PORT=${SEARCH_SUGGESTION_SERVICE_PORT}
      - COMMON_DATA_SERVICE_URL=http://common-data-service:${COMMON_DATA_SERVICE_PORT}
    expose:
      - ${SEARCH_SUGGESTION_SERVICE_PORT}
    ports:
      - ${SEARCH_SUGGESTION_SERVICE_PORT}:${SEARCH_SUGGESTION_SERVICE_PORT}

  react-ui:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: react-service-container
    stdin_open: true
    restart: always
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    environment:
      - REACT_APP_STRIPE_PUBLISH_KEY=${REACT_APP_STRIPE_PUBLISH_KEY}
      - REACT_APP_COMMON_DATA_SERVICE_PORT=${COMMON_DATA_SERVICE_PORT}
      - REACT_APP_ENVIRONMENT=${REACT_APP_ENVIRONMENT}
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql-db
      
