version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: atulkkushwaha92/ecommerce-react-ui
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
volumes:
  client: